[build]
command = "cp angular.netlify.json angular.json && npx nx build rl-ecommerce --configuration=production"
publish = "dist/apps/rl-ecommerce/browser"

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true
