[build]
  command = "npx nx build rl-ecommerce --configuration=production"
  publish = "dist/apps/rl-ecommerce/browser"
  base = "/"

  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    force = true